### ISSUE TITLE
1.20.1 ATM9整合包 加了Rock'n Roller崩溃

### ISSUE THREAD

**Issue by Achiyun** [ThinkingStudios/ItemScroller-Forge#2]
单独添加 孤独HUD Tweakerge MaFgLib/MaLiLib-Forge这三个没问题，加了Rock'n Roller 就崩溃

**Comment by TexBlock** [comment]
> 单独添加 孤独HUD Tweakerge MaFgLib/MaLiLib-Forge这三个没问题，加了Rock'n Roller 就崩溃

GIVE ME LOG, PLEASE!

**Comment by TexBlock** [comment]
> 单独添加 孤独HUD Tweakerge MaFgLib/MaLiLib-Forge这三个没问题，加了Rock'n Roller 就崩溃

GIVE ME LOG, PLEASE!

**Comment by CROAC233** [comment]
mc提示itemscroller需要malilib，而其未安装（？）fglib版本0.1.7, 1.19.2

> > 单独添加 孤独HUD Tweakerge MaFgLib/MaLiLib-Forge这三个没问题，加了Rock'n Roller 就崩溃
> 
> GIVE ME LOG, PLEASE!

**Comment by TexBlock** [comment]
fix in 0.1.1
