### ISSUE TITLE
1.20.1 cannot add recipe & hotkey issue

### ISSUE THREAD

**Issue by Nejtherry** [ThinkingStudios/ItemScroller-Forge#6]
LWJGL 3.3.1
MC 1.20.1
Forge 47.2.20

Mods: Other Masa forge ported mod by you and Curtain(Forge ported Carpet)

The recipe is not added to the recipe list(hotkey + midmouse bottom)
When pressing hotkey(set to GUI only) outside of GUI it is triggered and being toggled, cannot trigger the recipe list when pressing again in GUI, when it's triggered cannot close inside GUI must exit and then press again.

**Comment by TexBlock** [comment]
use latest version

**Comment by Nejtherry** [comment]
> use latest version

Thank you, I'll try it out.
