### ISSUE TITLE
Not working with MaFgLib 0.1.9

### ISSUE THREAD

**Issue by CrftTbls** [ThinkingStudios/ItemScroller-Forge#7]
1.20.1 Forge 47.2.20

mod
RocknRoller-0.1.2-mc1.20.1.jar
MaFgLib-0.1.9-mc1.20.1.jar

My apologies if you have already started to respond
Rockn Roller will not do anything when using the above version
Downgrade MaFgLib version to 0.1.8 and it works

**Comment by TexBlock** [comment]
fixed in RocknRoller latest version
